config/routes.rb
Rails.application.routes.draw do
  resources :productos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto Se creo de manera exitosa' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Se actualizo los datos del producto' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'El Producto ha sido eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:nombre, :d_item, :precio_item, :total_items, :direccion_ven, :vendedor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true) do |form| %>
  <% if producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :producto_nombre %>
  </div>

  <div class="field">
    <%= form.label :d_item %>
    <%= form.text_field :d_item, id: :producto_d_item %>
  </div>

  <div class="field">
    <%= form.label :precio_item %>
    <%= form.number_field :precio_item, id: :producto_precio_item %>
  </div>

  <div class="field">
    <%= form.label :total_items %>
    <%= form.number_field :total_items, id: :producto_total_items %>
  </div>

  <div class="field">
    <%= form.label :direccion_ven %>
    <%= form.text_field :direccion_ven, id: :producto_direccion_ven %>
  </div>

  <div class="field">
    <%= form.label :vendedor %>
    <%= form.text_field :vendedor, id: :producto_vendedor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Mostrar', @producto %> |
<%= link_to 'Regresar', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion del item</th>
      <th>Precio del item</th>
      <th>Total de items</th>
      <th>Direccion de vendedor</th>
      <th>Vendedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.d_item %></td>
        <td><%= producto.precio_item %></td>
        <td><%= producto.total_items %></td>
        <td><%= producto.direccion_ven %></td>
        <td><%= producto.vendedor %></td>
        <td><%= link_to 'Mostrar', producto %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', producto, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Añadir nuevo producto', new_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form', producto: @producto %>

<%= link_to 'Regresar', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</p>

<p>
  <strong>Descripcion del item:</strong>
  <%= @producto.d_item %>
</p>

<p>
  <strong>Precio del item:</strong>
  <%= @producto.precio_item %>
</p>

<p>
  <strong>Total de items:</strong>
  <%= @producto.total_items %>
</p>

<p>
  <strong>Direccion del vendedor:</strong>
  <%= @producto.direccion_ven %>
</p>

<p>
  <strong>Vendedor:</strong>
  <%= @producto.vendedor %>
</p>

<%= link_to 'Editar', edit_producto_path(@producto) %> |
<%= link_to 'Regresar', productos_path %>